### ISSUE TITLE
5.2 non functional requirements performance

### ISSUE THREAD

**Issue by renjiezhang** [GenevaS/CAS741#10]
@GenevaS @smiths 
In the Performance, you mentioned that time and space performance is not priority. I think you don't need to put the performance here because it is not a requirement. If you keep it there then you need to give it a fit criteria.

**Comment by GenevaS** [comment]
I don't see the point in stating a fit criterion for a class of requirements that are explicitly listed as not being considered. I believe that it would send mixed messages if I did this (i.e. Is it important? It says that it isn't, but there is a fit criterion/goal for it.)

The purpose of mentioning the non-functional requirements that are not being considered going forward is to make it explicit that those requirements were considered and marked as unimportant, rather than not being considered at all. The same reasoning was used for the reusability and portability non-functional requirements in this SRS. I got the idea from the medical imaging SRS that was used as a sample, and I thought it made the specification more rigorous and thorough.

What do you think @smiths ?

**Comment by smiths** [comment]
I agree with @GenevaS.  Specifying that a nonfunctional requirement, like performance, is not a priority is an appropriate part of a specification.  Given that it is not a priority, the absence of a fit criterion is fine.
