### ISSUE TITLE
Comments Added to SRS

### ISSUE THREAD

**Issue by smiths** [GenevaS/CAS741#11]
I've added comments to your SRS.tex file.  Please have a look at them.

**Comment by GenevaS** [comment]
Alright, I will work through the document in order.

I have removed the comment about ``svgnames`` and added types to the table of symbols. I have also updated the document so that it matches the template currently in the GitLab repo. Would you please have a look and let me know if the new type information makes sense and addresses your comment? Thanks!

Changes in commit 028218dbf6516d2c1c7ce31dc3f66795488c92f9.

**Comment by smiths** [comment]
Hello @GenevaS.  Yes, the type information that you have added is very helpful.  One thing that the types highlight is that you might consider using a sequence rather than a set of X and Y.  You are adding subscripts anyway.  The problem with the set is what connects the input variable to the function variable.  If you use sequence to do this, then you don't need the names of the variables to make the connection.

**Comment by GenevaS** [comment]
I chose set notation because that is the one that I am most familiar with. If I were to change ``X`` and ``Y`` to sequences, would you expect the notation change from ``x E X`` to ``any/some x in X`` or do you expect sequence notation explicitly (e.g. ``for some a_i in (a_i)0..n``?

**Comment by smiths** [comment]
Hello Geneva.  Yes, you can use the x \in X notation for sequences.  I don't use particularly sophisticated mathematics.  Normally a notation like that in HoffmanAndStrooper1995 (in the cas741 repo) works for me.  Sequences operations are given on page 38.

**Comment by GenevaS** [comment]
Ok, I think I've tracked down the biggest problem - I did not define a notation for a variable name or a variable name set. Does this statement make sense to you?

"The C^3 tool calculates ``R(f(V))`` of a user-defined ``f(V)`` given ``D(v), v \in V``. Each ``D(v)`` must be specified by the user in the initial version of this tool, otherwise the tool will assume that the user input set is incomplete and treat it as an error."

Where the notation is:

``v`` (No type) A variable name
``V`` (No type) A set of variable names
``D(v)`` ([R,R]) The domain of a variable ``v`` represented as a closed, real interval
``f(V)`` ({[R,R]_0, ..., [R,R]_n} -> [R,R]) A function of domains for a set of variables ``V`` that produces a closed, real interval
``R(f(V))`` ([R,R]) The range of ``f(V)`` represented as a closed, real interval

I think I should reserve the use of ``x`` and ``X`` for the theoretical models to match the associated source materials.

**Comment by smiths** [comment]
Yes, I like this better.  😄

**Comment by GenevaS** [comment]
Alright, I believe that I have finished renaming all of the relevant variables. Could you have a look at some of the most confusing sections and let me know if this new notation helps your understanding?

**Comment by smiths** [comment]
I do not have time to review your entire document, but I like the changes that I looked at.  The type information in particular is very helpful.

**Comment by GenevaS** [comment]
I understand. That's why I asked you to review the most confusing sections to see if the changes helped :) If you found those sections to be understandable now, I reasoned that the rest should be ok too (or close to). 

Was there anything else related to notation that you wanted me to work on?

**Comment by smiths** [comment]
No.  I have no suggestions at this time.

**Comment by GenevaS** [comment]
Alright. Thanks for all the help! I appreciate it :)
