### ISSUE TITLE
SRS Comments: Clarifying Functional Requirements

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#18]
\wss{It isn't clear how $D(x)$ will be entered.  Why not have your input just be
  the input variables of type interval.  The way you have written it, it appears
  that there are variables $x$ and a function that returns the domain of a given
  $x$.  If all you are looking for is upper and lower bounds for each variable,
  that would be easy to say.  You talk about converting to interval form in R2,
  so maybe I'm missing something.  Either way, it is confusing.  R8 is
  ambiguous.  Why wouldn't it be possible to verify $R$.  What are the potential
reasons that would be communicated to the user?}

**Comment by GenevaS** [comment]
All R1 is meant to say is that we somehow get the user's function and variable domains. I left the exact details unspecified because it felt more like a design decision than a requirement. The follow up requirement about converting the domain information to interval form is referring to the data definition for intervals that the C^3 tool understands.

For R8, the "verification" is with respect to R6 and R7 where a result is found (or not) and checked against the output data constraints. I am confused as to why this is the confusing one when it is the last in a series of related functional requirements.

**Comment by smiths** [comment]
For R1 my comments are related to your notation.  I'm not saying it is wrong, but it is confusing.  The connection between the variables in the set X and the domain of each variable relies on identifying the variable, but the variables aren't the focus of the input.  If you turn it around and focus on the variables, I think it will be clearer.  If your input is a sequence of variables of the interval type (using the I type specified in http://homes.esat.kuleuven.be/~optec/events/20090622_kozma.pdf), then I think you can make the inputs clearer.

If you like your notation, you can certainly keep it.  I just want you to think about other options that I think could be clearer.

As for as R8 goes, you should write your requirements so that they stand alone.  In this case, if R7 explicitly referenced the other requirements, you would be covered.  An explicit connection is better than an implied connection.

**Comment by GenevaS** [comment]
Alright, I will focus on closing Issue #11 (which has become the "fix the notation" issue) before pursuing this one further.

**Comment by GenevaS** [comment]
Now that the notation problem has been sorted out (Issue #11), does R1 make sense without further changes?

**Comment by smiths** [comment]
R1 is fine now.
