### ISSUE TITLE
Scope should mention restriction on division

### ISSUE THREAD

**Issue by smiths** [GenevaS/CAS741#19]
For division you aren't allowing mixed intervals.  You should say this in the scope section of your SRS.

**Comment by GenevaS** [comment]
This would be because mixed interval divisors do not result in closed intervals (at least one bound is infinity, which is open by definition). I do see why this should be in the scope because I also explicitly list the types of operators allowed in ``f(V)`` ahead of the assumptions list. I will expand the document scope to explain this.

**Comment by smiths** [comment]
Yes, you have good reason to exclude the mixed case.  I'm just suggesting that you make this explicit in the scope section.  I thought of it during your presentation because I hadn't realized you made this decision when I read your document.  I'm sure it is in there somewhere, but it is good to be explicit right up front.

**Comment by GenevaS** [comment]
Alright, I've added the information to the document. If there is no additional missing information related to this issue, please close it :)
