### ISSUE TITLE
Review Comments on Test Plan

### ISSUE THREAD

**Issue by smiths** [GenevaS/CAS741#26]
Comments on test plan are available in commit 708bb2c.

**Comment by GenevaS** [comment]
I've finished working through most of your comments, and I have a few questions:

- For the proof by induction, is it clear what I mean by ```f(V) = f_1(V) <op> f_2(V) by induction```? I'm not honestly sure what the type is of a proof by induction otherwise.
- How in-depth do you want the user testing description to be? I hesitate to do a full description because I expect the test will be both small and informal.

**Comment by smiths** [comment]
If you are talking about a proof, why is it listed as a test case?  Test cases are for dynamic execution.  If you are doing a "pen and paper" style proof, this would be under non-testing based verification.

For a description of the user testing it doesn't have to be in depth.  If your tests are going to be small and informal, you should explicitly say that.  Even for an informal test,  you can describe what material the testers will be given and what they will be asked to do.

**Comment by GenevaS** [comment]
Done and done.
