### ISSUE TITLE
Section 3.1: System Context

### ISSUE THREAD

**Issue by GenevaS** [GenevaS/CAS741#3]
Hi Professor.

If you are able, could you please have a look at my system context (Section 3.1)? Conceptually my project is fairly simple, so I expect this section to be shorter than what I am used to writing. That being said, I am not sure that my context description contains all the required information. Any feedback would be appreciated, especially if something is unclear or missing.

The latest version of the document can be found at: https://github.com/GenevaS/CAS741/blob/master/Doc/SRS/SRS.pdf

Thanks!

**Comment by smiths** [comment]
Hello @GenevaS.  If you wanted to, you could make your section shorter by avoiding duplication between the section's introductory paragraph and the itemized list.  You could also just say C^3 will detect syntax errors, instead of listing the types of syntax errors, like mismatched brackets.  However, the duplication that is there doesn't really seem to be a problem to me and being explicit about the types of possible syntax errors is helpful.  Overall, I like the section as it is written.

**Comment by GenevaS** [comment]
Ok, that helps a lot. Thank you for looking at this professor.
