### ISSUE TITLE
MIS User Input

### ISSUE THREAD

**Issue by icbicket** [GenevaS/CAS741#32]
Maybe you have a reason, but why is there no Input listed in the access program for the user input module? I think you could add either a filename string, a file, or a list of strings in the correct format.

**Comment by GenevaS** [comment]
I ended up coding a function that takes a file name as an input. Originally I had thought to enclose the entire input process in one function, where I would get the inputs or file names through a smaller control class. This ended up being more complicated than necessary because of my GUI, so I changed the definition. I will be updating the MIS document to reflect the changes.

**Comment by GenevaS** [comment]
Updated in e56549a170d98897e422842b3b8176ced8130a87.
