### ISSUE TITLE
MIS: Consolidate

### ISSUE THREAD

**Issue by icbicket** [GenevaS/CAS741#34]
Does Consolidate make the conversion between lists of strings and real numbers to feed to the state variables it creates? Say, ConvertAndCheckInputs takes in strings and lists of strings, but intervalStruct takes in a string and two real numbers, where is the conversion done?

You mention it a little in the transition in 10.4.3 for ConvertAndCheckInputs, but there's not a lot of detail here. What is a successful parse and consolidation process? Are there exceptions that can be raised here? (the input to ConvertAndCheckInputs would allow me to, say, enter ['f', '6'] as an interval, but this can't be converted to real numbers, how do you catch this?) How is the parsing done?

**Comment by GenevaS** [comment]
I handle most of the incorrect data type errors inside the appropriate conversion module, so this one need only worry about mismatched variable lists from the equation and interval definitions.

I have added a success code that is returned so that better error handling can be done in the calling module. I have also added an explicit description of what is happening when this function is called.
