### ISSUE TITLE
MIS: general comments

### ISSUE THREAD

**Issue by icbicket** [GenevaS/CAS741#36]
Just a couple of general comments on the MIS, overall, nice job!

In 7.4.3, GetInputMethod shows up (there is an assumption about it), is this the same as GetUserInputs in 7.3.1? Otherwise, where does it come from?

In 11.4.3, can you define what supportedOps and eqRange are? Are you treating them as data types? State variables?

In 6.4.2, you have Solver,CalculateRange, is this meant to be FindRange (from 11.3.2)?

You could consider organizing your modules in the order in which they appear in Control Flow, it might make the document easier to follow.

I see now that you are using IntervalConversion and EquationConversion in your Consolidation module. This answers one of my earlier comments, but can you make it clearer exactly what the Consolidation module does with these, and how it calls them? Neither conversion module is really mentioned in the access programs for Consolidation.

**Comment by GenevaS** [comment]
- I have added qualifiers to all the functions in the ControlFlow pseudo code to clarify which module they are coming from
- I have made supportedOps an exported constant and added a definition for the calculation of eqRange (renamed to range)
- Yes. I have updated the ControlFlow pseudo code with this as well.
- Organizing the document that way wouldn't make sense anymore because some modules are designed such that they shouldn't be accessed directly from ControlFlow
- Updated the process flow of the Consolidate module. Hopefully this will clarify what everything is doing.

Thanks for the help!
