### ISSUE TITLE
missing symbol in IM3

### ISSUE THREAD

**Issue by renjiezhang** [GenevaS/CAS741#9]
@GenevaS @smiths 

In table of symbol, the author does not give the definition of Symbol M in IM3

**Comment by GenevaS** [comment]
The usage of ``M`` in the IM for "Multiplication of closed, real intervals" is to make the equation easier to read. It only exists within that context, which is why it is also only defined there. Since it is essentially a temporary variable, it doesn't belong in the global symbolic constants table.

For reference, the equation reads:

``x_mul = min(M), y_mul = max(M), where M = {x_1 * y_1, x_1 * y_2, x_2 * y_1, x_2 * y_2}``

Using a temporary variable ``M`` here stops the duplication of the much longer ``x_1 * y_1, x_1 * y_2, x_2 * y_1, x_2 * y_2``.

What do you think @smiths ?

**Comment by smiths** [comment]
Although I understand your point @GenevaS, I like all symbols to be in the table of symbols, even the temporary ones.  You never know when a reader might want to check a symbol.  Rather than judge what is important and what is not, it is easier to just include everything in the table of symbols.  You can define M as an intermediate variable, only used for the purpose of making the specification clearer.

**Comment by GenevaS** [comment]
Fair enough. Added in 4d549f5e07f850c15253f00bf5f69dbf783d4ab5:

"`M` -> A temporary variable for aiding in the readability of equations"
